# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  app:
    build:
      context: .
      target: build  # Use build stage for development
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    volumes:
      - ./src:/app/src:ro  # Mount source code for hot reload
      - ~/.m2:/root/.m2    # Mount Maven cache
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: url_shortener_dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
