spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener_dev
    username: devuser
    password: devpass
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.urlshortener: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  base-url: http://localhost:8080
