spring:
  application:
    name: url-shortener-service
  
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.urlshortener: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Custom application properties
app:
  base-url: ${BASE_URL:http://localhost:8080}
  short-code-length: 6
  max-url-length: 2048
  default-expiration-days: 365
