spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    com.urlshortener: WARN
    org.springframework: WARN

app:
  base-url: http://localhost:8080
  short-code-length: 4
