spring:
  application:
    name: url-shortener-service
        
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}
  
  # Redis configuration for Docker
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    database: 0
    timeout: 2000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.urlshortener: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Custom application properties
app:
  base-url: ${BASE_URL:http://localhost:8080}
  short-code-length: 6
  max-url-length: 2048
  default-expiration-days: 365
