spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/url_shortener}
    username: ${DB_USERNAME:urluser}
    password: ${DB_PASSWORD:urlpass}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        connection:
          provider_disables_autocommit: false
    open-in-view: false
        
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.urlshortener: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Custom application properties
app:
  base-url: ${BASE_URL:http://localhost:8080}
  short-code-length: 6
  max-url-length: 2048
  default-expiration-days: 365
